services:

  db:
    image: postgres:15
    container_name: piscineds_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./secrets/postgres_password:/run/secrets/postgres_password:ro

volumes:
  db_data:
